### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/purple-prism#1]
# User Flow
### Create Account
1. enter npub or nsec
   a. just npub would allow users to create prisms and attach to posts in another client
   b. nsec would allow users to create prisms and post from Purple Prism
2. Do we have user create password? Or do we do like zapit.live and and have user input `username` and `npub`, then on signup we give them a login key
3. Account created -> sign in

### Sign In
1. User provides necessary credentials (npub + password?; nsec?; login key?)
2. Directed to home page with "Create Prism" and "Post a Note"

### Create Prism
1. prism name
2. add members
   a. destination
      - depending on payment provider we can support different destination type
      - start with LNURL
  b. split - integer normalized to a percentage.
     - user inputs integer and sees percentage. Percentage changes and user changes prism member splits
4. Create a receiving address for prism
   a. I think this will require us to host a LNURL server or find a service that can create lightning addresses for us through an API
      - our own server will probably be necessary so that we can listen for payments to that address and know when to pay out the prism
5. "Prism created! Attach it to a note" --> Post a note

### Post a Note
1. Text box for posting **kind 1**
2. Dropdown to pick prism to attach
3. "Post"
   a. Which relays do we post to?

---

# Architecture

#### Prisms (6 days)
- [ ] GET prism
- [ ] POST prism
- [ ] PUT prism
- [ ] DELETE prism

#### Users (2 days)
- [ ] POST user
   - creates a new user in our db
   - requires npub for creating prisms
   - optional: require nsec for posting with attached prisms
- [ ] GET user
   - returns user info
      - prisms, npub, LNURL

### Payments - Strike, LNBits, or Zebedee (4 days)
- [ ] listen for zaps to prism
- [ ] payout prism members on zap

#### Stretch Goals

- [ ] Public prisms
- [ ] count total zaps on a prism
- [ ] 

## Things to Research
- [ ] how to create LNURL's for users.
- [ ] Do we need to run our own lnurl server
- [ ] How to securely store nsec
